version: '3'

services:
    db:
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=steam

    phpmyadmin:
        container_name: steam-phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - 7344:80
        depends_on:
            - db
        environment:
            - PMA_HOST=db
            - PMA_USER=root
            - PMA_PASSWORD=password
