name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
jobs:
  deploy:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
      php-version: [8.1]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check PHP Version
      run: php -v

    - name: Check the Symfony console
      run: /usr/local/php8.1/bin/php bin/console about

    - name: Clear cache
      run: /usr/local/php8.1/bin/php bin/console cache:clear

    - name: Cache warmup
      run: /usr/local/php8.1/bin/php bin/console cache:warmup

    - name: Coding standards checks (php_codesniffer + php-cs-fixer)
      run: /usr/local/php8.1/bin/php ./vendor/bin/php-cs-fixer fix --allow-risky=yes --dry-run

    - name: Static analysis of PHP code (PHPStan)
      run: /usr/local/php8.1/bin/php ./vendor/bin/phpstan analyse src --memory-limit 1G
  
    - name: Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.1.1
      with:
        server: ${{ secrets.SERVER }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        local-dir: ./
        server-dir: /www/steam
        exclude: |
          .git
          vendor
          node_modules
